(()=>{
const HKEY='aikatsu_scan_history_v1', MKEY='aikatsu_qr_map_v1', SKEY='aikatsu_state_v1', CKEY='aikatsu_cards_v1';
let stream=null,running=false,lastRaw='',lastSeen=0,sessionId='',detector=null,raf=0;
const hist=()=>JSON.parse(localStorage.getItem(HKEY)||'[]'), map=()=>JSON.parse(localStorage.getItem(MKEY)||'{}');
const saveHist=x=>localStorage.setItem(HKEY,JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function cardFor(raw){const m=map();if(m[raw])return m[raw];const hit=raw.match(/\b(E\d+-\d{2,3})\b/i);return hit?hit[1].toUpperCase():''}
function cardMeta(num){const cs=JSON.parse(localStorage.getItem(CKEY)||'[]');return cs.find(c=>c.number===num)||null}
function addOwned(num){if(!num)return;const c=cardMeta(num);if(!c)return;const s=JSON.parse(localStorage.getItem(SKEY)||'{}');const id=c.id;s[id]=s[id]||{qty:0,want:false,trade:false};s[id].qty=(s[id].qty||0)+1;localStorage.setItem(SKEY,JSON.stringify(s))}
function toast(t,ok=true){const e=document.querySelector('#scanToast');if(!e)return;e.textContent=t;e.className='scan-toast show '+(ok?'ok':'ng');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),500)}
function record(raw){const now=Date.now();if(raw===lastRaw&&now-lastSeen<1800)return;lastRaw=raw;lastSeen=now;const num=cardFor(raw),c=cardMeta(num);if(num&&c)addOwned(num);const h=hist();h.push({scan_no:h.length+1,session_id:sessionId,scanned_at:new Date().toISOString(),card_number:num||'',rarity:c?.rarity||'',series:c?.series||'',qr_raw:raw});saveHist(h);toast(num?num+' 所持に追加しました ♡':'未登録QRを読み取りました',!!num);renderHistory()}
async function ensureDecoder(){if('BarcodeDetector'in window){try{detector=new BarcodeDetector({formats:['qr_code']});return}catch(e){}}if(!window.jsQR){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jsQR/1.4.0/jsQR.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}}
async function start(){sessionId='S'+new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14);document.querySelector('#scannerOverlay').classList.add('open');try{await ensureDecoder();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=document.querySelector('#scanVideo');v.srcObject=stream;await v.play();running=true;loop()}catch(e){toast('カメラを開始できません',false)}}
function stop(){running=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;document.querySelector('#scannerOverlay').classList.remove('open');location.reload()}
async function loop(){if(!running)return;const v=document.querySelector('#scanVideo');try{if(v.readyState>=2){if(detector){const rs=await detector.detect(v);if(rs[0]?.rawValue)record(rs[0].rawValue)}else if(window.jsQR){const c=document.querySelector('#scanCanvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=v.videoWidth;c.height=v.videoHeight;x.drawImage(v,0,0);const d=x.getImageData(0,0,c.width,c.height),r=jsQR(d.data,d.width,d.height,{inversionAttempts:'dontInvert'});if(r?.data)record(r.data)}}}catch(e){}raf=requestAnimationFrame(loop)}
function bind(raw){const n=prompt('このQRのカード番号を入力（例：E1-01）');if(!n)return;const num=n.trim().toUpperCase();if(!cardMeta(num)){alert('カード番号が一覧にありません');return}const m=map();m[raw]=num;localStorage.setItem(MKEY,JSON.stringify(m));const h=hist();h.forEach(x=>{if(x.qr_raw===raw&&!x.card_number){x.card_number=num;const c=cardMeta(num);x.rarity=c?.rarity||'';x.series=c?.series||''}});saveHist(h);toast(num+' に紐付けました ♡');renderHistory()}
function renderHistory(){const box=document.querySelector('#historyList');if(!box)return;const h=hist().slice().reverse().slice(0,100);box.innerHTML=h.length?h.map(x=>`<div class="history-row"><span class="hn">#${x.scan_no}</span><b>${esc(x.card_number||'未判定')}</b><span>${new Date(x.scanned_at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span>${x.card_number?'':`<button data-bind="${encodeURIComponent(x.qr_raw)}">紐付け</button>`}</div>`).join(''):'<div class="history-empty">まだ履歴はありません</div>';box.querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>bind(decodeURIComponent(b.dataset.bind)))}
function csv(){const h=hist();if(!h.length)return;const cols=['scan_no','session_id','scanned_at','card_number','rarity','series','qr_raw'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const text='\ufeff'+cols.join(',')+'\n'+h.map(r=>cols.map(k=>q(r[k])).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='aikatsu_scan_history_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function clearHistory(){if(confirm('スキャン履歴をすべて削除しますか？')){saveHist([]);renderHistory()}}
function ui(){if(document.querySelector('#qrScanBtn'))return;const top=document.querySelector('.toolbar');if(!top)return;const b=document.createElement('button');b.id='qrScanBtn';b.className='primary';b.textContent='▣ QR';top.appendChild(b);b.onclick=start;document.body.insertAdjacentHTML('beforeend',`<div id="scannerOverlay" class="scanner-overlay"><div class="scan-head"><b>QR連続スキャン</b><button id="scanClose">×</button></div><div class="camera"><video id="scanVideo" playsinline muted></video><canvas id="scanCanvas"></canvas><div class="scan-guide"></div><div id="scanToast" class="scan-toast"></div></div><div class="scan-actions"><button id="csvBtn">CSV出力</button><button id="clearHist">履歴削除</button></div><div class="scan-note">読み取ったカードは即＋1。同じQRを映しっぱなしにしても連打しません。未判定QRはあとからカード番号に紐付けできます。</div><div id="historyList" class="history-list"></div></div>`);document.querySelector('#scanClose').onclick=stop;document.querySelector('#csvBtn').onclick=csv;document.querySelector('#clearHist').onclick=clearHistory;renderHistory()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();