const C='aikatsu-manager-v11';
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(C).then(c=>c.addAll(['./manifest.webmanifest']))) });
self.addEventListener('activate',e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==C).map(k=>caches.delete(k))))])));
self.addEventListener('fetch',e=>{
 const u=new URL(e.request.url);if(u.origin!==location.origin)return;
 if(e.request.mode==='navigate'||u.pathname.endsWith('/index.html')||u.pathname.endsWith('/aikatsu-card-manager/')){
  e.respondWith(fetch(e.request).then(async r=>{let html=await r.text();
   const css=`<style id="ui-fix-v11">
:root{--pink:#ff70a9;--pink2:#ff94bf;--pale:#fff3f8;--ink:#5a3b48}body{font-family:"Hiragino Maru Gothic ProN","Hiragino Kaku Gothic ProN","Yu Gothic",sans-serif!important;color:var(--ink)!important;background:#fffafd!important}h1{color:#e95891!important;font-weight:800!important;letter-spacing:.04em!important;text-shadow:0 2px 0 #fff!important}input,button,select{font-family:inherit!important}.card{overflow:hidden;border:1px solid #f5dce6!important;border-radius:15px!important;box-shadow:0 3px 10px rgba(221,111,155,.08)!important}.card .card-image-stage{width:100%;aspect-ratio:476/670;display:flex;align-items:center;justify-content:center;overflow:hidden;background:transparent}.card .card-image-stage>img{display:block;margin:0!important;background:transparent;object-fit:contain;max-height:none!important}.card .card-image-stage>img.normal-card{width:100%!important;height:100%!important;max-width:100%!important;transform:none!important}.card .card-image-stage>img.accessory-card{width:calc(670 / 476 * 100%)!important;height:calc(476 / 670 * 100%)!important;max-width:none!important;transform:rotate(90deg)!important;transform-origin:center center}.card.image-missing .card-image-stage{display:none}.grid{align-items:start}.card strong{color:#684653!important;font-weight:800!important}.card button{border-color:#f2d8e2!important;color:#d95086!important;background:#fff!important;font-weight:700!important}.card button.active,.card button[aria-pressed="true"]{background:linear-gradient(135deg,var(--pink2),var(--pink))!important;color:#fff!important;border-color:var(--pink)!important;box-shadow:0 2px 6px rgba(255,112,169,.22)!important}.tabs>button,.tabs>select{border-color:#f1d6e1!important;color:#c94d7e!important;background:#fff!important;font-weight:700!important}.tabs>button.active{background:linear-gradient(135deg,#ff91bc,#ff69a4)!important;color:#fff!important;border-color:#ff75aa!important;box-shadow:0 3px 8px rgba(255,105,164,.22)!important}.tabs>select{color:#744c5c!important}.progress{background:#f5e8ed!important}.progress>div{background:linear-gradient(90deg,#ff9bc2,#ff68a4)!important}input[type="search"],input[type="text"]{border-color:#f0d7e1!important;border-radius:16px!important;background:#fff!important;color:#684653!important}.refresh,.update,#refresh{background:linear-gradient(135deg,#ff91bc,#ff69a4)!important;color:#fff!important;border:0!important;font-weight:800!important;box-shadow:0 3px 8px rgba(255,105,164,.2)!important}
@media(min-width:700px){.grid{grid-template-columns:repeat(5,minmax(0,1fr))!important}}
@media(max-width:699px){h1{font-size:25px!important}.tabs{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:6px!important;overflow:visible!important;padding-top:10px!important}.tabs>button{width:100%!important;min-width:0!important;height:38px!important;padding:6px 0!important;border-radius:999px!important;white-space:nowrap!important;font-size:13px!important;line-height:1!important}.tabs>select{grid-column:1/-1!important;width:100%!important;height:40px!important;padding:6px 14px!important;border-radius:999px!important;text-align:center!important;font-size:14px!important}}
</style>`;
   const js=`<script id="card-image-script-v11">(()=>{const BASE='https://dcd.aikatsu.com/encore/images/cardlist/card/';function fallbacks(img){const alt=(img.alt||'').trim();if(!/^E1-(81|82)$/.test(alt))return[];return [BASE+alt+'_R.webp',BASE+alt+'_PR.webp',BASE+alt+'.webp',BASE+alt+'_N.png',BASE+alt+'_R.png',BASE+alt+'_PR.png',BASE+alt+'.png']}function fix(){document.querySelectorAll('.card>img:not([data-oriented])').forEach(img=>{img.dataset.oriented='1';const card=img.closest('.card'),wrap=document.createElement('div');wrap.className='card-image-stage';img.parentNode.insertBefore(wrap,img);wrap.appendChild(img);img._fallbacks=fallbacks(img);img._fallbackIndex=0;const orient=()=>{card&&card.classList.remove('image-missing');const accessory=img.naturalWidth>img.naturalHeight;img.classList.toggle('accessory-card',accessory);img.classList.toggle('normal-card',!accessory)};const missing=()=>{if(img._fallbackIndex<img._fallbacks.length){img.src=img._fallbacks[img._fallbackIndex++];return}card&&card.classList.add('image-missing')};img.addEventListener('load',orient);img.addEventListener('error',missing);if(img.complete){img.naturalWidth?orient():missing()}})}new MutationObserver(fix).observe(document.documentElement,{childList:true,subtree:true});fix()})()</script>`;
   html=html.replace('</head>',css+'</head>').replace('</body>',js+'</body>');return new Response(html,{status:r.status,statusText:r.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})
  }).catch(()=>caches.match('./index.html')))
 }
});